[
    {
        "name": "manley mahi",
        "description": "Our longtime love affair with the EL84 has never sounded tighter, faster, or deeper than it does in the MAHI. Larger B+ rail storage means control, impact, and slamming bass punch. Nimble and lively, the MAHI delivers 20 Watts in TRIODE mode and 40 Watts in Ultra-Linear mode through our own custom transformers, engineered and wound at Manley Labs. Variable Feedback switch provides a sonic palette ranging from sweet and seductive to powerful and rockin’. Sold in pairs. (Mahi-Mahi!)",
        "price": "£4550",
        "image": "images/products/poweramplifiers/manley_mahi.jpg",
        "category": "power amplifiers",
        "manufacturer": "manley",
        "manufacturerLink": "https://www.manley.com/mahi",
        "warrenty": "3 years",
        "deliveryTime": "1-4 working days",
        "id": "1"
    },
    {
        "name": "manley neoclassic 300b",
        "description": "Our most esoteric product is THE 300B PREAMPLlFIER. This is the first and only preamp to feature these classic tubes. We had been designing the 300B into small power amps for many years and have always had great respect for the smooth natural sound of this tube. However, a single 300B provides truly appropriate power and voltage swing for headphones and makes a remarkable line driver. Here is where the impedances are not too low and the power requirements are not too high: ideal for this kind of tube in a single-ended configuration. This was the genesis of a new preamp.",
        "price": "£6700",
        "image": "images/products/poweramplifiers/manley_neoclassic300b.jpg",
        "category": "power amplifiers",
        "manufacturer": "manley",
        "manufacturerLink": "https://www.manley.com/hifi/neo3br",
        "warrenty": "3 years",
        "deliveryTime": "1-6 working days",
        "id": "2"
    },
    {
        "name": "manley snapper",
        "description": "100 Watts at full power across the entire frequency band from a quartet of EL34’s in a fully differential circuit topology is only achievable with an impressive 19-layer output transformer designed and wound by us here at Manley Labs, of course. Very cleverly, the Snapper’s unique fully balanced topology can be driven via the XLR inputs or by the unbalanced RCA’s with no sonic penalty either way. Until you have experienced these beauties, you have no idea how great these Snappers sound. Strong and natural, like real music. ",
        "price": "£4716",
        "image": "images/products/poweramplifiers/manley_snapper.jpg",
        "category": "power amplifiers",
        "manufacturer": "manley",
        "manufacturerLink": "https://www.manley.com/hifi/msn",
        "warrenty": "8 years",
        "deliveryTime": "1-9 working days",
        "id": "3"
    },
    {
        "name": "parasound halo a23",
        "description": "Parasound’s Halo A 23 Amplifier is the ultimate combination of cutting edge technology, superb craftsmanship, and stunning industrial design. With high current Class A/AB amplification, smooth sounding MOSFET drivers, and balanced XLR inputs, this mighty amp will make any speaker sound better than ever before. The A 23 two channel amplifier boasts 125 watts of THX Ultra 2 certified power per channel, and it looks as amazing as it sounds. Whether it’s movies or music, the A 23 will knock your socks off!",
        "price": "£1999",
        "image": "images/products/poweramplifiers/parasound_haloa23.jpg",
        "category": "power amplifiers",
        "manufacturer": "parasound",
        "manufacturerLink": "https://www.parasound.com/a23.php",
        "warrenty": "4 years",
        "deliveryTime": "1-6 working days",
        "id": "4"
    },
    {
        "name": "creek classic cd",
        "description": "The latest incarnation of Creek's mid-price CD player design is an evolution of the tried and trusted CD50Mk2. Adhering nicely to the 'if it ain't broke, don't fix it' school of design, the Classic incorporates a few choice modifications over its predecessor in order to keep things competitive.",
        "price": "£100",
        "image": "images/products/cd_players/creek_classic_cd.jpg",
        "category": "cd players",
        "manufacturer": "creek",
        "manufacturerLink": "https://www.creekaudio.com/",
        "warrenty": "2 years",
        "deliveryTime": "1-3 working days",
        "id": "5"
    },
    {
        "name": "creek destiny 2",
        "description": "The Destiny 2 CD Player is Creek’s high-end model and represents a significant improvement over the original, highly respected, Destiny model. It uses all the sound optimisation techniques and components collected by Mike Creek and his team of analogue and digital electronics engineers during their many years in the hi-fi industry. It is designed to suit a wide range of amplifiers, but Creek recommends the new Destiny 2 integrated amp as a cosmetic and performance quality match. It can also be used together with any of the Evolution amps and controlled by Creek’s new SRC3 system remote control.",
        "price": "£150",
        "image": "images/products/cd_players/creek_Destiny_CD.jpg",
        "category": "cd players",
        "manufacturer": "creek",
        "manufacturerLink": "https://www.creekaudio.com/product-archive/destiny-2-cd-player/",
        "warrenty": "5 years",
        "deliveryTime": "1-6 working days",
        "id": "6"
    },
    {
        "name": "creek evolution 2",
        "description": "The EVOLUTION 2 builds upon the strengths of the original by replacing older technology parts and retaining the best bits, to enhance its overall performance. It is designed to cosmetically match the EVOLUTION 2 Integrated Amplifier, although it will work perfectly with any make hi-fi amplifier.",
        "price": "£200",
        "image": "images/products/cd_players/creek_evo_cd.jpg",
        "category": "cd players",
        "manufacturer": "creek",
        "manufacturerLink": "https://www.creekaudio.com/product-archive/evolution-2-cd/",
        "warrenty": "4 years",
        "deliveryTime": "1-7 working days",
        "id": "7"
    },
    {
        "name": "exposure 2010s2 cd",
        "description": "The Exposure 2010S2 player has classic proportions and a traditional fascia. In the front, made from a slab of aluminum large holes for the tray and display were cut. Below the latter (which is blue) we have six buttons operating the drive functions. To the left there is a seventh button, the power switch – a mechanical one, without standby. This old-fashioned solution is now increasingly ecological… On the back we have a pair of RCA sockets with the analog signal – but those are bit too close together – an IEC power socket and digital ones – BNC and TOSLINK. The BNC socket is of very high quality.",
        "price": "£130",
        "image": "images/products/cd_players/exposure_2010S_CD.gif",
        "category": "cd players",
        "manufacturer": "exposure",
        "manufacturerLink": "https://exposurehifi.com/",
        "warrenty": "4 years",
        "deliveryTime": "1-5 working days",
        "id": "8"
    },
    {
        "name": "creek classic dvd",
        "description": "The latest incarnation of Creek's mid-price DVD player design is an evolution of the tried and trusted CD50Mk2. Adhering nicely to the 'if it ain't broke, don't fix it' school of design, the Classic incorporates a few choice modifications over its predecessor in order to keep things competitive.",
        "price": "£100",
        "image": "images/products/dvd_players/creek_classic.jpg",
        "category": "dvd players",
        "manufacturer": "creek",
        "manufacturerLink": "https://www.creekaudio.com/",
        "warrenty": "2 years",
        "deliveryTime": "1-3 working days",
        "id": "9"
    },
    {
        "name": "exposure 2010s2 dvd",
        "description": "The Exposure 2010S2 player has classic proportions and a traditional fascia. In the front, made from a slab of aluminum large holes for the tray and display were cut. Below the latter (which is blue) we have six buttons operating the drive functions. To the left there is a seventh button, the power switch – a mechanical one, without standby. This old-fashioned solution is now increasingly ecological… On the back we have a pair of RCA sockets with the analog signal – but those are bit too close together – an IEC power socket and digital ones – BNC and TOSLINK. The BNC socket is of very high quality.",
        "price": "£130",
        "image": "images/products/dvd_players/exposure_2010S.jpg",
        "category": "dvd players",
        "manufacturer": "exposure",
        "manufacturerLink": "https://exposurehifi.com/",
        "warrenty": "4 years",
        "deliveryTime": "1-5 working days",
        "id": "10"
    },
    {
        "name": "parasound model d 200",
        "description": "Recently appeared Parasound components of the new series of Halo, the hallmark of which are eye-catching design and advanced circuitry. But do not miss your attention and components of the classic series. In fact they are a quarter-century ago brought us from San Francisco worldwide fame. Player D200 - a fresh neoclassical interpretation of traditional Parasound electronics engineering solutions. The design is in the style of professional audio - tough, laconic, no frills (by the way, using special mounting whales this player can be mounted in a standard rack). The same principles are reviewed and functional D200.",
        "price": "£118",
        "image": "images/products/dvd_players/parasound_d200.jpg",
        "category": "dvd players",
        "manufacturer": "parasound",
        "manufacturerLink": "https://parasound.com/vintage/d200.php",
        "warrenty": "3 years",
        "deliveryTime": "1-6 working days",
        "id": "11"
    },
    {
        "name": "parasound halo d3",
        "description": "Parasound's Halo line of home theater amps and processors is a tough act to follow. But the Halo D 3 Universal disc player is a worthy addition to the Halo series. The D 3 offers the ultimate feature set for DVD-Video, DVD-Audio, and SACD playback. Talk about a no-compromise movie and music machine!",
        "price": "£155",
        "image": "images/products/dvd_players/parasound_halod3.jpg",
        "category": "dvd players",
        "manufacturer": "parasound",
        "manufacturerLink": "https://parasound.com/vintage/d3.php",
        "warrenty": "2 years",
        "deliveryTime": "1-4 working days",
        "id": "12"
    },
    {
        "name": "creek a50i",
        "description": "The A50i integrated amplifier continues Creek’s tradition of exemplary musical performance at non-insane prices. Integrated amps have always been the nucleus of UK audio systems and there are numerous reasons for their dominance. One is simple value, coupled with a high Non-Screw-Up-ability Factor. One saves the price and hassle of choosing an interconnect, and also the possibility of mismatching the preamp to the power amp when using items from different manufacturers. The only trade-off is the need to use longer speaker cables in some installations.",
        "price": "£604",
        "image": "images/products/integrated_amplifiers/creek_a50I.jpg",
        "category": "integrated amplifiers",
        "manufacturer": "creek",
        "manufacturerLink": "https://www.creekaudio.com/",
        "warrenty": "3 years",
        "deliveryTime": "1-2 working days",
        "id": "13"
    },
    {
        "name": "creek evolution 5350 se",
        "description": "The Evolution 5350 integrated amplifier has been designed to fill the gap left by the Classic range, between the entry level Evolution 2 and the top of the range Destiny. It has borrowed technology from both the Evolution 2  integrated amplifier and Classic 5350SE and is styled to match the Evolution 2 CD Player and Evolution 2 Tuner.",
        "price": "£476",
        "image": "images/products/integrated_amplifiers/creek_classic5350SE.jpg",
        "category": "integrated amplifiers",
        "manufacturer": "creek",
        "manufacturerLink": "https://www.creekaudio.com/product-archive/evolution-5350/",
        "warrenty": "3 years",
        "deliveryTime": "1-7 working days",
        "id": "14"
    },
    {
        "name": "creek destiny 2",
        "description": "The Destiny 2 integrated amplifier is Creek’s high-end model and represents a significant improvement over the original, highly respected, Destiny model. It uses all the sound optimisation techniques and components collected by Mike Creek and his team of analogue electronics engineers during their many years in the Hi-Fi industry.",
        "price": "£242",
        "image": "images/products/integrated_amplifiers/creek_destinyamp.jpg",
        "category": "integrated amplifiers",
        "manufacturer": "creek",
        "manufacturerLink": "https://www.creekaudio.com/product-archive/destiny-2-integrated-amplifier/",
        "warrenty": "4 years",
        "deliveryTime": "1-6 working days",
        "id": "15"
    },
    {
        "name": "manley snapper integrated amp",
        "description": "100 Watts at full power across the entire frequency band from a quartet of EL34’s in a fully differential circuit topology is only achievable with an impressive 19-layer output transformer designed and wound by us here at Manley Labs, of course. Very cleverly, the Snapper’s unique fully balanced topology can be driven via the XLR inputs or by the unbalanced RCA’s with no sonic penalty either way. Until you have experienced these beauties, you have no idea how great these Snappers sound. Strong and natural, like real music.",
        "price": "£4716",
        "image": "images/products/integrated_amplifiers/manley_snapper.jpg",
        "category": "integrated amplifiers",
        "manufacturer": "manley",
        "manufacturerLink": "https://www.manley.com/hifi/msn",
        "warrenty": "8 years",
        "deliveryTime": "1-9 working days",
        "id": "16"
    },
    {
        "name": "manley stingray",
        "description": "From our most advanced evolution of the Stingray, expect even more coherent bass definition and solid brawn from the larger high voltage energy storage. The EL84 output stage can be switched between 20 Watts of TRIODE power or 40 Watts of Ultra-Linear mode push-pull operation. The headphone output takes advantage of the entire amplifier and every ounce of attention to detail we have poured into this fantastic design. RF remote control included.",
        "price": "£3600",
        "image": "images/products/integrated_amplifiers/Manley_Stingray.jpg",
        "category": "integrated amplifiers",
        "manufacturer": "manley",
        "manufacturerLink": "https://www.manley.com/hifi/m2st",
        "warrenty": "5 years",
        "deliveryTime": "1-7 working days",
        "id": "17"
    },
    {
        "name": "creek obh 22",
        "description": "The function of the Creek OBH-22 passive preamplifier is to provide input selection and volume adjustment to a Hi-Fi system from an armchair, via infra-red remote control. The unit can also be controlled directly from the front panel. The OBH-22 consists of a high quality motorised volume potentiometer, and two stereo relays which select the desired input plus tape output, together with a muting relay that can short the signals to ground. A built-in micro-controller decodes the infra-red signals transmitted by the handset and translates them into commands which activate the motorised potentiometer and the muting and input selection relays. After each operation, the micro-controller turns itself off to avoid any possibility of interfering with the main music signal. LED's are used to indicate the status and mode of operation. The OBH-22 is purely passive and does not introduce any gain or distortion into the signal path. It is therefore suitable to be used as a control pre-amplifier, provided the sensitivity of the power amplifier that is being used is high enough to be driven directly from the source. i.e. CD player or tuner etc. The volume control can be operated manually at any time, whether the OBH-22 is powered or not, but without power only Line 1 can be utilised.",
        "price": "£495",
        "image": "images/products/preamplifiers/Creek_OBH_22_Passive_Preamp.jpg",
        "category": "preamplifiers",
        "manufacturer": "creek",
        "manufacturerLink": "https://www.creekaudio.com/",
        "warrenty": "4 years",
        "deliveryTime": "1-2 working days",
        "id": "18"
    },
    {
        "name": "parasound classic 7100",
        "description": "The Model 7100 Surround Controller is a THX Ultra2 certified, 7.1 channel surround sound processor (SSP) capable of decoding all the current surround sound formats. The 7100 incorporates a number of THX processing modes; THX Cinema is designed to accommodate the differences between theater and home acoustics and THX Ulta2 Cinema converts 5.1 material into 7.1 output. THX Surround EX with additional rear surround speakers plays back 6.1 material. Similarly THX Music Mode takes 5.1 recordings and plays them back over a 7.1 system. And finally for the gamers, THX Games Mode is for surround effects for video games.",
        "price": "£319",
        "image": "images/products/preamplifiers/parasound_classic7100.jpg",
        "category": "preamplifiers",
        "manufacturer": "parasound",
        "manufacturerLink": "https://parasound.com/vintage/7100.php",
        "warrenty": "4 years",
        "deliveryTime": "1-5 working days",
        "id": "19"
    },
    {
        "name": "parasound halo p3",
        "description": "Parasound's goal with the HALO lineup was to build on Parasound's already respected platform, while bringing a new level of performance and visual distinction to the Parasound family. The first in the HALO lineup is the '3' series made up of the P 3 preamplifier, A 23 amplifier, and T 3 tuner. Parasound will be adding additional models to the HALOs which will include monoblocks, a surround processor, multi-channel amplifiers, and disc players. The designer of the '3' series was given the flexibility to choose quality internal parts for power supplies and audio paths, which should give birth to some exceptional products.",
        "price": "£257",
        "image": "images/products/preamplifiers/parasound_halop3.jpg",
        "category": "preamplifiers",
        "manufacturer": "parasound",
        "manufacturerLink": "https://parasound.com/vintage/p3.php",
        "warrenty": "4 years",
        "deliveryTime": "1-2 working days",
        "id": "20"
    },
    {
        "name": "pro-ject pre box s2",
        "description": "Pre Box S2 Digital marks a new era for our S-series components. For the very first time we are using a dual mono configuration with the highest class D/A converters of ESS Sabre. Their flagship DAC-chip ensures highest class audio in a small and affordable package. This DAC is capable of high resolution audio up to 32bit/768kHz PCM and DSD512! Pre Box S2 Digital is also the very first of our devices to support hardware MQA unfolding. It’s also the premiere of our proprietary Optimum transient digital filter and our proprietary clock circuitry design. Digital audio is the art of time, with our new proprietary clock design we have managed jitter rates of unrivalled 100 Femtoseconds, this easily outperforms many renowned and respected audiophile clock generators!",
        "price": "£188",
        "image": "images/products/preamplifiers/Project_prebox.jpg",
        "category": "preamplifiers",
        "manufacturer": "pro-ject",
        "manufacturerLink": "https://www.project-audio.com/en/product/pre-box-s2-digital/",
        "warrenty": "3 years",
        "deliveryTime": "1-6 working days",
        "id": "21"
    },
    {
        "name": "bösendorfer vcs",
        "description": "The Bösendorfer VC7 is a loudspeaker in the Vienna Acoustics Range. A two-way system with two treble speakers, four bass drivers/mid-range speakers and two Acoustic Sound Boards. The floor standing range comprises slim elegant enclosures featuring resonant side panels which radiate sound in a radial pattern, not just to the front as in conventional designs.",
        "price": "£251",
        "image": "images/products/speakers/boesendorfer_vcs_wall.gif",
        "category": "speakers",
        "manufacturer": "bösendorfer",
        "manufacturerLink": "https://www.boesendorfer.com/",
        "warrenty": "7 years",
        "deliveryTime": "1-2 working days",
        "id": "22"
    },
    {
        "name": "epos m5",
        "description": "The M5 is a shielded, biwirable, two-way bass-reflex design. The 1\" dome tweeter has a gold-anodized diaphragm of aluminum alloy terminated with a polyamide suspension. Ferrofluid is used to improve the tweeter's power handling and smooth its frequency response. The tweeter's rear-cavity loading and high-efficiency neodymium magnet are claimed to improve its transient response and eliminate temporal smearing. The 5.4\" woofer cone is made of an injection-molded polymer that includes a small amount of talc to optimize stiffness. The aluminum chassis is die-cast, and has a phase plug. The M5 is available in light or dark cherry or black—my dark-cherry samples were elegant and attractive.",
        "price": "£251",
        "image": "images/products/speakers/epos_m5.gif",
        "category": "speakers",
        "manufacturer": "epos",
        "manufacturerLink": "https://www.eposaudio.com/",
        "warrenty": "5 years",
        "deliveryTime": "1-4 working days",
        "id": "23"
    },
    {
        "name": "harbeth hi 7es-2",
        "description": "Introduced in 1988, the original HL Compact 7 was the first model to use Harbeth’s Radial, a patented, propriety synthetic compound—now widely used in the company’s woofers and midrange drivers—that Shaw considers far superior in resolution and low coloration to the polypropylene that Harbeth’s founder, Dudley Harwood, pioneered at the BCC. Shaw introduced a revised Compact 7 in 1999, with incremental improvements. When he turned his attention to it yet again last year, the result was to advance an already excellent design to an even higher level. How much higher? I’ll make a naked grab for your attention: between about 80Hz and 10kHz there is nearly nothing wrong with the frequency response of the 7ES-3. A couple of absolutely miniscule glitches and anomalies remain, but they do not matter, as they are scarcely audible even with critical listening. Indeed, for sheer neutrality the 7ES-3 rivals the Harbeth Monitor 40 (my colleague Robert Greene’s reference), and in the 2kHz– 4kHz range even trumps my reference Quads—by a very tiny margin to be sure, but a deuce trump is still a trump.",
        "price": "£317",
        "image": "images/products/speakers/harbeth_hl7es2.jpg",
        "category": "speakers",
        "manufacturer": "harbeth",
        "manufacturerLink": "https://harbeth.co.uk/",
        "warrenty": "2 years",
        "deliveryTime": "1-7 working days",
        "id": "24"
    },
    {
        "name": "harbeth monitor 30",
        "description": "The Monitor 30 was developed to drop-in to the space occupied by the BBC LS5/9. The objective of the Monitor development 30 was to provide a recognisably BBC sound yet in a relatively small box with truly incredible resolution and clarity, perfect integration of the drivers, and a solid bass (for catching rumble and hum). The sweet midrange and a extended and smooth top end make the Monitor 30 a pleasure to use and set it far apart from similar size cabinets.",
        "price": "£142",
        "image": "images/products/speakers/harbeth_monitor30.jpg",
        "category": "speakers",
        "manufacturer": "harbeth",
        "manufacturerLink": "https://harbeth.co.uk/",
        "warrenty": "6 years",
        "deliveryTime": "1-7 working days",
        "id": "25"
    },
    {
        "name": "harbeth p3esr",
        "description": "Harbeth’s development team has, once again, redefined what is possible from this use anywhere loudspeaker. The completed redesign maximises the performance potential of the Harbeth exclusive 110mm RADIAL2™ Cone Technology. Delivering breathtaking transparency, accurate bass and dynamic integration across the audio spectrum. Arguably one of the most advanced speakers in its class, the P3ESR XD is capable of being used in a wide range of listening environments and is optimised to present an easy electrical load to even low powered amplifiers. Get ready to re-experience your music collection from one of the most groundbreaking speakers ever released by Harbeth.",
        "price": "£180",
        "image": "images/products/speakers/harbeth_p3es2.jpg",
        "category": "speakers",
        "manufacturer": "harbeth",
        "manufacturerLink": "https://harbeth.co.uk/p3esr-xd-loudspeaker/",
        "warrenty": "1 years",
        "deliveryTime": "1-3 working days",
        "id": "26"
    },
    {
        "name": "jolida jd 102b",
        "description": "Fully Integrated Stereo Amplifier: Input 900mV driving 20 watts, maximum 25 watts output. Multiple Inputs: CD and Aux (for Tuner, TV, DVD Player, VCR, Tape Recorder, Computer and etc). Tape Loop and Pre-Out are available on request. Right and Left Stereo Balance Control: + 20dB at both right and left front panel control. Custom Wound Audio Transformers with a core of German grain oriented silicon steel. 15th generation proprietary design. Secondary can be configured for a 4 ohm or 8 ohm load. Top Panel Bias Testing Terminals with Bias Adjustment Controls. State of the Art Components: Gold plated RCA input jacks, gold plated five way speaker connectors.",
        "price": "£548",
        "image": "images/products/tube_amplifiers/jolida_JD102b.jpg",
        "category": "tube amplifiers",
        "manufacturer": "jolida",
        "manufacturerLink": "https://www.jolida.com/",
        "warrenty": "7 years",
        "deliveryTime": "1-2 working days",
        "id": "27"
    },
    {
        "name": "jolida jd 202a",
        "description": "Fully Integrated Stereo Amplifier: Input 350mV driving 40 watts, maximum 60 watts output. Multiple Inputs: Front mounted selector switch-CD, Tuner and Aux (for TV, DVD Player, VCR or computer). Custom Wound Audio Transformers with a core of German grain oriented silicon steel. 15th generation proprietary design. Secondary can be configured for a 4 ohm or 8 ohm load. State of the Art Components: ALPS or Panasonic audio potentiometer, gold plated RCA input jacks, gold plated five way speaker connectors. Low Feedback Design: Only 9 dB.",
        "price": "£287",
        "image": "images/products/tube_amplifiers/jolida_JD202a.jpg",
        "category": "tube amplifiers",
        "manufacturer": "jolida",
        "manufacturerLink": "https://www.jolida.com/",
        "warrenty": "6 years",
        "deliveryTime": "1-2 working days",
        "id": "28"
    },
    {
        "name": "jolida jd 300b",
        "description": "An offering of a Single Ended Triode (SET) integrated amplifier for your listening pleasure. Cosmetically the unit is finished in white metal (oxidized/sandblasted aluminum). The unit has four inputs and two fixed outputs with 4 and 8 ohm, five way speaker taps. One feature not found on many SET’s is a remote control. We have found with the volume variability in different CD discs, the remote comes in handy with a 9 watt amplifier. The unit has high speed soft recovery diodes with German capacitors. Matched with an efficient speaker, the clarity of the highs and midrange are matched with the weight in the bottom end. If music is art for your ears, the JD 300B may be your sound painter.",
        "price": "£863",
        "image": "images/products/tube_amplifiers/jolida_JD300b.jpg",
        "category": "tube amplifiers",
        "manufacturer": "jolida",
        "manufacturerLink": "https://www.jolida.com/",
        "warrenty": "7 years",
        "deliveryTime": "1-2 working days",
        "id": "29"
    },
    {
        "name": "jolida jd 302b",
        "description": "Fully Integrated Stereo Amplifier: Input 500mV driving 50 watts, maximum 75 watts output. Multiple Inputs: Front mounted selector switch-CD, Tape Recorder, Tuner and Aux (for TV, DVD Player, VCR or Computer). Right and Left Stereo Balance Control: + 50dB at both right and left front panel control. Custom Wound Audio Transformers with a core of German grain oriented silicon steel. 15th generation proprietary design. Secondary can be configured for a 4 ohm or 8 ohm load. Top panel bias testing terminal with bias adjustment controls. State of the Art Components: ALPS audio potentiometer, gold plated RCA input jacks. Low Feedback Design: Only 5 dB.",
        "price": "£750",
        "image": "images/products/tube_amplifiers/jolida_JD302b.jpg",
        "category": "tube amplifiers",
        "manufacturer": "jolida",
        "manufacturerLink": "https://www.jolida.com/",
        "warrenty": "4 years",
        "deliveryTime": "1-6 working days",
        "id": "30"
    },
    {
        "name": "jolida jd 502b",
        "description": "Fully Integrated Stereo Amplifier: Input 600mV driving 60 watts, maximum 85 watts output. Multiple Inputs: Front mounted selector switch-CD, Tape Recorder, Tuner and Aux (for TV, DVD Player, VCR or Computer). Right and Left Stereo Balance Control: + 50dB at both right and left front panel control. Custom Wound Audio Transformers with a core of German grain oriented silicon steel. 15th generation proprietary design. Secondary can be configured for a 4 ohm or 8 ohm load. Top panel bias testing terminal with bias adjustment controls. State of the Art Components: ALPS audio potentiometer, gold plated RCA input jacks. Low Feedback Design: Only 5 dB.",
        "price": "£806",
        "image": "images/products/tube_amplifiers/jolida_JD502b.jpg",
        "category": "tube amplifiers",
        "manufacturer": "jolida",
        "manufacturerLink": "https://www.jolida.com/",
        "warrenty": "4 years",
        "deliveryTime": "1-2 working days",
        "id": "31"
    },
    {
        "name": "pro-ject debut 3 blue",
        "description": "Precision belt drive with synchronous motor. New DC power supply with ultra precision frequency DC-driven AC generator (like Speed Box) for ultimate speed stability. New TPE motor suspension. Ortofon OM5e cartridge. Speeds: 33, 45 (manual switching. 8.6\" Aluminium tonearm.",
        "price": "£169",
        "image": "images/products/turnables/Pro_ject_Debut_3_bl.jpg",
        "category": "turnables",
        "manufacturer": "pro-ject",
        "manufacturerLink": "https://www.project-audio.com/",
        "warrenty": "3 years",
        "deliveryTime": "1-6 working days",
        "id": "32"
    },
    {
        "name": "pro-ject debut 3 red",
        "description": "Precision belt drive with synchronous motor. New DC power supply with ultra precision frequency DC-driven AC generator (like Speed Box) for ultimate speed stability. New TPE motor suspension. Ortofon OM5e cartridge. Speeds: 33, 45 (manual switching. 8.6\" Aluminium tonearm.",
        "price": "£169",
        "image": "images/products/turnables/Pro_ject_Debut_III_red_1.jpg",
        "category": "turnables",
        "manufacturer": "pro-ject",
        "manufacturerLink": "https://www.project-audio.com/",
        "warrenty": "3 years",
        "deliveryTime": "1-6 working days",
        "id": "33"
    },
    {
        "name": "pro-ject debut 3 yellow",
        "description": "Precision belt drive with synchronous motor. New DC power supply with ultra precision frequency DC-driven AC generator (like Speed Box) for ultimate speed stability. New TPE motor suspension. Ortofon OM5e cartridge. Speeds: 33, 45 (manual switching. 8.6\" Aluminium tonearm.",
        "price": "£169",
        "image": "images/products/turnables/Pro_ject_Debut_III_yellow_1.jpg",
        "category": "turnables",
        "manufacturer": "pro-ject",
        "manufacturerLink": "https://www.project-audio.com/",
        "warrenty": "3 years",
        "deliveryTime": "1-6 working days",
        "id": "34"
    },
    {
        "name": "pro-ject rpm 5",
        "description": "RPM 5 Carbon utilises a radical concept with a lot of innovations, that originate from its big brother RPM 9 Carbon: A low resonance chassis holds a newly designed inverted platter bearing with ceramic ball for further reduced rumble. The acoustically inert platter is made from acrylic. An outboard 15V AC motor is smoothly driven using an ultra-precision AC generator with DC power supply for further enhanced speed stability. The classy 9“ Evo tonearm, which is made from carbon fibre is suitable for any high-quality MM or MC cartridge. A TPE-damped counterweight eliminates unwanted resonances.",
        "price": "£288",
        "image": "images/products/turnables/Pro_ject_rpm_5.jpg",
        "category": "turnables",
        "manufacturer": "pro-ject",
        "manufacturerLink": "https://www.project-audio.com/en/product/rpm-5-carbon/",
        "warrenty": "2 years",
        "deliveryTime": "1-7 working days",
        "id": "35"
    },
    {
        "name": "pro-ject rpm 10",
        "description": "The RPM 10 Carbon uses a new extra heavy chassis which features a special CNC machined MDF plate that incorporates hard resin coated steel pellets to form an extra heavy precise sandwich construction. A special complex heat treatment and a carbon surface coating ensures superior low resonance levels. The mass-loaded chassis is effectively decoupled from its surface via the included Ground it Carbon and its magnetic feet. With two magnets located in the feet, the turntable is practically floating. The studs in the feet are only used for keeping them centered. Due to this unique feature the turntable is perfectly decoupled from the surface it is placed on. Combined with a new special polished aluminium platter with internal TPE damping and a vinyl layer on top, the inverted ceramic main bearing delivers an absolute stable turntable speed with extra low rumble. The extra heavy outboard motor unit is equipped with a precise motor control and features a built-in switch between 33 & 45 rpm. Last but not least the non-compromise 10“ Evo tonearm with conical carbon-fibre armtube and inverted bearing design ensures perfect tracking, even with demanding cartridges. Highly flexible top-grade copper internal wiring. Delivered with topgrade 5P phono cable „Connect it CC“ with RCA plugs (XLR as an option).",
        "price": "£153",
        "image": "images/products/turnables/Pro_ject_rpm10.jpg",
        "category": "turnables",
        "manufacturer": "pro-ject",
        "manufacturerLink": "https://www.project-audio.com/en/product/rpm-10-carbon/",
        "warrenty": "4 years",
        "deliveryTime": "1-5 working days",
        "id": "36"
    }
]



